# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tjapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('WebUrl', models.CharField(max_length=250)),
                ('WebUrlContactUs', models.URLField(max_length=250)),
                ('CustomerServicePhone', models.URLField(max_length=25)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_routes', to='tjapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DelayInMinutes', models.PositiveSmallIntegerField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_statutes', to='tjapp.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='tjapp.Route')),
            ],
        ),
        migrations.AddField(
            model_name='routestatus',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_statutes', to='tjapp.Station'),
        ),
        migrations.AddField(
            model_name='routestatus',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
