# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tjapp', '0003_auto_20171119_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
