# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tjapp', '0004_auto_20171119_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='Route',
        ),
        migrations.AddField(
            model_name='route',
            name='DepartureStation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_stations_dep', to='tjapp.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='DestinationStation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route_stations_dest', to='tjapp.Station'),
        ),
        migrations.AddField(
            model_name='route',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
