# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjapp', '0005_auto_20171119_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='DestinationStation',
            new_name='ArrivalStation',
        ),
        migrations.AlterField(
            model_name='company',
            name='CustomerServicePhone',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='WebUrl',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
