# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjapp', '0008_auto_20171203_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='ActualArrivalTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
